describe('Testing RegistrApp', () => {
    beforeEach(()=>{
        cy.visit('/login')
    })
    it('Testing login alumno',()=>{
        cy.get('ion-input[name="usuario"]').should('be.visible')
        cy.get('ion-input[name="usuario"]').type('lcepeda@duoc.cl')
        cy.get('ion-input[name="password"]').type('1234')
        cy.contains('Ingresar').click()
        cy.url().should('include','/home-alumno')
        cy.wait(2000)
    })
    it('Testing login profesor',()=>{
        cy.get('ion-input[name="usuario"]').should('be.visible')
        cy.get('ion-input[name="usuario"]').type('mcarrasco@duoc.cl')
        cy.get('ion-input[name="password"]').type('1234')
        cy.contains('Ingresar').click()
        cy.url().should('include','/home-profesor')
        cy.wait(2000)
    })
    it('Testing reporteria',()=>{
        cy.get('ion-input[name="usuario"]').should('be.visible')
        cy.get('ion-input[name="usuario"]').type('mcarrasco@duoc.cl')
        cy.get('ion-input[name="password"]').type('1234')
        cy.contains('Ingresar').click()
        cy.contains('Reportería').click()
        cy.wait(2000)
        cy.contains('Ir a reporte').click()
        cy.wait(2000)
        cy.contains('Descargar PDF').click()
    })
    it('Testing generacion qr',()=>{
        cy.get('ion-input[name="usuario"]').should('be.visible')
        cy.get('ion-input[name="usuario"]').type('mcarrasco@duoc.cl')
        cy.get('ion-input[name="password"]').type('1234')
        cy.contains('Ingresar').click()
        cy.contains('QR').click()
        cy.wait(2000)
        cy.contains('Generar QR').click()
        cy.wait(2000)
        cy.contains('Estado QR').click()
        cy.wait(2000)
        cy.get('ion-button[name="volver"]').click()
        cy.contains('Finalizar Clase').click()
    })
    it('Testing listar curso',()=>{
        cy.get('ion-input[name="usuario"]').should('be.visible')
        cy.get('ion-input[name="usuario"]').type('mcarrasco@duoc.cl')
        cy.get('ion-input[name="password"]').type('1234')
        cy.contains('Ingresar').click()
        cy.contains('Listar Cursos').click()
        cy.contains('Ver Asistencia').click()
    })
  })